import { useState } from 'react';
import { Reveal, WorkspacePanel } from './VisualSystem.jsx';
import { articles, services } from './content.js';
import { publicPath } from './paths.js';
import './solutions.css';

export function LineIcon({type = 'app'}) {
  const paths = {app: 'M5 3h14v18H5z M5 8h14 M9 5.5h6 M8 12h3v3H8z M14 12h2 M14 15h2 M8 18h8', bot: 'M4 4h16v12H9l-5 4V4z M8 8h8 M8 12h5', shop: 'M4 8h16l-2-5H6L4 8z M5 8v13h14V8 M9 21v-7h6v7', account: 'M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z M4 21v-3c0-6 16-6 16 0v3', calendar: 'M4 5h16v16H4z M8 2v6 M16 2v6 M4 10h16 M8 14h2 M14 14h2 M8 18h2', loyalty: 'M12 3 21 9l-9 12L3 9l9-6z M3 9h18 M8 9l4 12 4-12', system: 'M3 3h6v6H3z M15 15h6v6h-6z M15 3h6v6h-6z M9 6h6 M18 9v6 M6 9v9h9'};
  return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[type] || paths.app}/></svg>;
}
const More = ({href, children = 'Подробнее'}) => <a className="text-link" href={publicPath(href)}>{children}<span aria-hidden="true">→</span></a>;

export function FormatVisual({bot = false}) {
  return <svg className="format-visual" viewBox="0 0 520 260" fill="none" aria-hidden="true"><g stroke="#363d4c" strokeWidth="1.2">
    {bot ? <><path d="M64 75h104m183 100h105M262 113v35" strokeDasharray="4 5"/><rect x="168" y="38" width="183" height="76" rx="9" fill="#101319"/><path d="M190 62h96m-96 15h133m-133 15h63"/><rect x="168" y="148" width="183" height="74" rx="9" fill="#121924"/><path d="M190 172h117m-117 17h79" stroke="#7195ff"/><circle cx="64" cy="75" r="18" fill="#101319"/><path d="m57 75 5 5 9-11" stroke="#7195ff"/><circle cx="456" cy="175" r="18" fill="#101319"/><path d="m449 175 5 5 9-11" stroke="#7195ff"/></> : <><rect x="117" y="30" width="284" height="199" rx="9" fill="#101319"/><path d="M117 63h284M185 63v166"/><path d="M133 46h31M132 83h35m-35 17h27m-27 17h31"/><rect x="204" y="83" width="79" height="70" rx="5"/><rect x="298" y="83" width="79" height="70" rx="5"/><path d="M204 172h128m-128 15h93"/><rect x="298" y="198" width="79" height="13" rx="4" fill="#233455" stroke="#4d6495"/><path d="m231 117 9 9 18-22m66 13h26m-13-13v26" stroke="#7195ff"/></>}
  </g></svg>;
}

export function Formats(){return <section className="container growth-section" id="formats"><Reveal><h2>Иногда нужен интерфейс.<br/><span className="quiet">Иногда достаточно диалога.</span></h2><p className="section-lead">Выбираем формат под задачу, а не наоборот.</p></Reveal><div className="format-grid">{[[false,'Telegram Mini Apps','Каталог, личный кабинет, запись или сервис — когда пользователю нужен полноценный интерфейс.','telegram-mini-apps'],[true,'Telegram-боты','Заявки, уведомления и автоматизация — когда задача решается сообщениями и кнопками.','telegram-bots']].map(([bot,title,text,slug])=><Reveal className="format-panel" key={slug}><FormatVisual bot={bot}/><div className="format-copy"><h3>{title}</h3><p>{text}</p><More href={'/services/'+slug}/></div></Reveal>)}</div><p className="format-note">Mini App и бот могут работать вместе: интерфейс — в приложении, коммуникация — в диалоге.</p></section>}

export function DataFlow(){return <div className="data-flow" aria-label="Заказ из Mini App передаётся через API в CRM, затем бот отправляет статус"><div><LineIcon/><b>Mini App</b><span>Создаёт заказ</span></div><i aria-hidden="true">→</i><div><LineIcon type="system"/><b>API</b><span>Проверяет данные</span></div><i aria-hidden="true">→</i><div><LineIcon type="account"/><b>CRM</b><span>Меняет статус</span></div><i aria-hidden="true">→</i><div><LineIcon type="bot"/><b>Бот</b><span>Уведомляет</span></div></div>}

const solutionItems = [['shop','Telegram-магазин','Каталог, корзина, заказы и личный кабинет.','telegram-commerce'],['account','Личный кабинет','Документы, статусы, подписки и история действий.','telegram-mini-apps'],['calendar','Запись и бронирование','Услуга, время, подтверждение и напоминание.','telegram-mini-apps'],['loyalty','Программа лояльности','Баллы, уровни и персональные предложения.','telegram-mini-apps'],['bot','Бизнес-бот','Заявки, уведомления и автоматизация процессов.','telegram-bots'],['system','Сервис для бизнеса','Своя логика: от внутреннего инструмента до клиентского продукта.','telegram-mini-apps']];
export function SolutionsList({full=false}) {return <section className="container growth-section" id="solutions">{!full&&<Reveal><h2>Что можно собрать<br/><span className="quiet">внутри Telegram.</span></h2></Reveal>}<Reveal className="motion-list"><div className="solutions-list">{solutionItems.map(([icon,title,text,slug])=><a href={publicPath('/services/'+slug)} className="solution-row" key={title}><LineIcon type={icon}/><div><h3>{title}</h3><p>{text}</p></div><span className="quiet" aria-hidden="true">↗</span></a>)}</div>{!full&&<More href="/services">Все решения</More>}</Reveal></section>}

export function Comparison(){return <section className="container growth-section comparison" id="comparison"><Reveal><div className="split-heading"><h2>Бот или Mini App?<br/><span className="quiet">Зависит от задачи.</span></h2><p>Важен путь пользователя: ответить на вопрос или управлять продуктом на экране.</p></div></Reveal><Reveal className="motion-pair"><div className="comparison-table"><div><h3><LineIcon type="bot"/>Бот</h3><p>Когда сценарий линейный.</p><ul><li>Оставить заявку или заполнить анкету</li><li>Получить уведомление о событии</li><li>Выполнить служебный запрос</li></ul><More href="/services/telegram-bots">О разработке ботов</More></div><div><h3><LineIcon/>Mini App</h3><p>Когда нужен интерфейс.</p><ul><li>Сравнить товары и собрать заказ</li><li>Выбрать время в календаре</li><li>Открыть кабинет и документы</li></ul><More href="/services/telegram-mini-apps">О разработке Mini Apps</More></div></div><div className="section-tail"><p>Для сложного сценария соединяем оба формата.</p><More href="/contact">Помочь выбрать формат</More></div></Reveal></section>}

export function Pricing(){return <section className="container growth-section" id="pricing"><Reveal><div className="split-heading"><h2>Сначала задача.<br/><span className="quiet">Потом оценка.</span></h2><p>Стоимость разработки зависит от сценариев, серверной логики и интеграций — не только от количества экранов.</p></div></Reveal><Reveal className="motion-list"><div className="estimate-list">{[['Telegram-бот','Диалог, автоматические действия и связь с системами.'],['Telegram Mini App','Интерфейс, данные, роли и пользовательские сценарии.'],['Mini App + бот','Единый продукт с уведомлениями и внешними интеграциями.']].map(([title,text])=><div key={title}><h3>{title}</h3><p>{text}</p><span>Оценка по задаче</span></div>)}</div><div className="section-tail"><p>Для оценки нужны основной сценарий и список систем.</p><More href="/contact">Получить оценку</More></div></Reveal></section>}

export function ConceptPreview(){return <section className="container growth-section"><Reveal><div className="split-heading"><h2>От интерфейса<br/><span className="quiet">к целому сценарию.</span></h2><p>Показываем действие пользователя и то, что происходит за экраном.</p></div></Reveal><Reveal className="motion-diagram"><a href={publicPath("/cases/sever-supply")} className="concept-feature"><div><span className="concept-label">Концепт · B2B · Mini App + бот</span><h3>Север.Снабжение</h3><p>Повторный заказ материалов: каталог, согласование, личный кабинет и уведомление о доставке.</p><span className="text-link">Смотреть проект →</span></div><FormatVisual/></a></Reveal></section>}

export function JournalList({full=false}) {return <section className="container growth-section">{!full&&<Reveal><h2>Разбираем Telegram<br/><span className="quiet">с продуктовой стороны.</span></h2></Reveal>}<Reveal className="motion-list"><div className="journal-list">{Object.entries(articles).map(([slug,item],i)=><a href={publicPath('/journal/'+slug)} key={slug}><span className="journal-number">0{i+1}</span><h3>{item.title}</h3><span aria-hidden="true">↗</span></a>)}</div>{!full&&<More href="/journal">Все материалы</More>}</Reveal></section>}

export function BotDemo(){const [step,setStep]=useState(0);return <div className="bot-demo"><div className="bot-demo-top"><LineIcon type="bot"/><b>Сервис заявок</b><span>Интерактивный концепт</span></div><div className="bot-conversation" aria-live="polite"><p className="bot-bubble">Здравствуйте. Что нужно сделать?</p>{step>0&&<p className="bot-bubble user-bubble">Оставить заявку</p>}{step===1&&<p className="bot-bubble">Выберите тему обращения.</p>}{step===2&&<><p className="bot-bubble user-bubble">Обсудить интеграцию</p><p className="bot-bubble">Заявка сформирована. В рабочем продукте она будет передана ответственному.</p></>}</div><div className="bot-controls">{step===0?<button onClick={()=>setStep(1)}>Оставить заявку <span>→</span></button>:step===1?<><button onClick={()=>setStep(2)}>Обсудить интеграцию <span>→</span></button><button onClick={()=>setStep(0)}>Назад</button></>:<button onClick={()=>setStep(0)}>Начать заново <span>↻</span></button>}</div><p className="demo-disclosure">Демо: сообщения и заявки никуда не отправляются.</p></div>}

export function ServiceContent({slug}) {const item=services[slug];return <><section className="container growth-section service-explanation"><Reveal><div className="split-heading"><h2>{item.heading}</h2><p>{item.intro}</p></div></Reveal><Reveal><div className="service-showcase">{slug==='telegram-bots'?<BotDemo/>:<WorkspacePanel/>}<div className="service-use-cases">{item.points.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></Reveal></section><section className="container growth-section"><Reveal><h2>Что входит в разработку.</h2></Reveal><Reveal className="motion-list"><div className="scope-list">{item.scope.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></Reveal></section><section className="container growth-section"><Reveal><div className="split-heading"><h2>Один продукт.<br/><span className="quiet">Связанные действия.</span></h2><p>Mini App, бот и системы компании используют согласованные данные. Доступность API и права доступа проверяем до разработки.</p></div></Reveal><Reveal className="motion-flow"><DataFlow/><More href="/journal/mini-app-or-bot">Как выбрать формат</More></Reveal></section><section className="container growth-section faq-grid"><Reveal><h2>Вопросы о разработке.</h2></Reveal><Reveal><div className="faq-list">{item.faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></Reveal></section><Pricing/></>}

export function ArticleContent({slug}){const item=articles[slug];return <article className="container editorial"><aside><span>В этом материале</span><nav aria-label="Содержание статьи">{item.sections.map(([title],i)=><a key={title} href={'#part-'+i}>{title}</a>)}</nav></aside><div>{item.sections.map(([title,...paragraphs],i)=><section key={title} id={'part-'+i}><h2>{title}</h2>{paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<div className="article-related"><h2>От выбора к разработке</h2><More href="/services/telegram-mini-apps">Telegram Mini Apps</More><More href="/services/telegram-bots">Telegram-боты</More></div><p className="article-source">Документация платформы: <a href="https://core.telegram.org/bots/webapps">Telegram Mini Apps</a> и <a href="https://core.telegram.org/bots/faq">Bots FAQ</a>.</p></div></article>}
